# ------------------- Registry Namespace ------------------- #
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
# ------------------- Registry Persistent Volume ------------------- #
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: registry
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
# ------------------- Registry Persistent Volume Claim ------------------- #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 30Gi
---
# ------------------- Registry Deployment ------------------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.6.2
          env:
            - name: REGISTRY_HTTP_SECRET
              value: omgsecurity
            - name: REGISTRY_HTTP_ADDR
              value: ":5000"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: image-store
              mountPath: "/var/lib/registry"
              subPath: "registry"
      volumes:
        - name: image-store
          persistentVolumeClaim:
            claimName: docker-registry-pvc
---
# ------------------- Registry Nginx Ingress Service ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: registry
spec:
  ports:
    - name: registry
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: docker-registry
  type: LoadBalancer
